name: shikshaarchana
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+13

environment:
  sdk: '>=2.17.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  get: ^4.6.6 # Replace LATEST_VERSION with the latest from pub.dev (e.g., ^4.6.6)
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  firebase_storage: ^12.4.7
  bottom_navy_bar: ^6.0.0
  #persistent_bottom_nav_bar_v2: ^6.0.1
  #persistent_bottom_nav_bar: ^5.0.2
  device_info_plus: ^11.4.0
  carousel_slider: ^5.1.1
  cloud_firestore: ^5.6.9
  audioplayers: ^6.4.0 # Consider specifying a version constraint
  image_picker: ^1.1.2
  provider: ^6.1.1
  shared_preferences: ^2.0.18
  webview_flutter: ^4.13.0
  flutter_native_image: ^0.0.6+1 # REMEMBER: This package is discontinued. Plan to replace it.
  dropdown_button2: ^2.1.3
  fluttertoast: ^8.2.2
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  # path_provider: ^2.1.1
  flutter_screenutil: ^5.9.3 # Replace LATEST_VERSION with the latest from pub.dev (e.g., ^5.9.3)
  url_launcher: ^6.0.10
  cupertino_icons: ^1.0.2
  persistent_bottom_nav_bar: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # You can check if a newer version is available
  flutter_launcher_icons: ^0.14.3 # You can check if a newer version is available

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/locale/
    - assets/classcontent/class1/
    - assets/classcontent/class4/
    - assets/classcontent/class6/
    - assets/classcontent/class7/
    - assets/classcontent/class8/