// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4bNR5Yc2KownvDy0xraSAI3Xl4hrpF5Q',
    appId: '1:797558520303:web:29e3a5b756c1467d835e1a',
    messagingSenderId: '797558520303',
    projectId: 'sikhsha-archana',
    authDomain: 'sikhsha-archana.firebaseapp.com',
    storageBucket: 'sikhsha-archana.appspot.com',
    measurementId: 'G-6WQWD4VX29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbYQMI8lPFFZWXSzKlJ-JVR_iYNpAaYXc',
    appId: '1:797558520303:android:f226d1be112ca178835e1a',
    messagingSenderId: '797558520303',
    projectId: 'sikhsha-archana',
    storageBucket: 'sikhsha-archana.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeNndigd8JL5rcIDa2cIdzMPFMqsS8D-M',
    appId: '1:797558520303:ios:e1c36cc51e58f4ca835e1a',
    messagingSenderId: '797558520303',
    projectId: 'sikhsha-archana',
    storageBucket: 'sikhsha-archana.appspot.com',
    androidClientId: '797558520303-bsbb0bhbad04p2is9924b237jgggkpmk.apps.googleusercontent.com',
    iosClientId: '797558520303-gv5fnu5nmbqmr9qq75difliu01ecosc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.shikshaarchana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeNndigd8JL5rcIDa2cIdzMPFMqsS8D-M',
    appId: '1:797558520303:ios:e1c36cc51e58f4ca835e1a',
    messagingSenderId: '797558520303',
    projectId: 'sikhsha-archana',
    storageBucket: 'sikhsha-archana.appspot.com',
    androidClientId: '797558520303-bsbb0bhbad04p2is9924b237jgggkpmk.apps.googleusercontent.com',
    iosClientId: '797558520303-gv5fnu5nmbqmr9qq75difliu01ecosc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.shikshaarchana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4bNR5Yc2KownvDy0xraSAI3Xl4hrpF5Q',
    appId: '1:797558520303:web:79541e4b3d8a2ed2835e1a',
    messagingSenderId: '797558520303',
    projectId: 'sikhsha-archana',
    authDomain: 'sikhsha-archana.firebaseapp.com',
    storageBucket: 'sikhsha-archana.appspot.com',
    measurementId: 'G-L5S7T8JB49',
  );
}
